### ISSUE TITLE
Particles

### ISSUE THREAD

**Issue by lunar1us** [Cold-Development/EnderScythe#1]
It seems that particles do not work if the item name is changed from its original name. The issue persists even after restarting the server or using the /enderscythe reload command.

1. Load the server having the plugin loaded
2. In the config file change the item's name
3. Use /enderscythe reload command
4. Observe that once the name is changed, the particles are not working anymore

**Comment by padrewin** [comment]
This will be fixed in a future update.
There's an issue about the "custom" item identifier.
